#!/usr/bin/env python

#
# generate cells along eigenmodes
# (run calculations separately for all cells)
# read in data from phonopy
# calculate resonant Raman intensity for various modes
# i.e. two dielectric functions per mode
#

import sys

import datetime

from displace import displace
from calcTensors import calcTensors
from calcSpectrum import calcSpectrum
#from plotSpectrum import plotSpectrum

sys.dont_write_bytecode = True

if __name__ == '__main__':

    print("")
    print("  _____                             _____       ")     
    print(" |  __ \                           |  __ \      ")     
    print(" | |__) |__ _ _ __ ___   __ _ _ __ | |__) |   _ ")
    print(" |  _  // _` | '_ ` _ \ / _` | '_ \|  ___/ | | |")
    print(" | | \ \ (_| | | | | | | (_| | | | | |   | |_| |")
    print(" |_|  \_\__,_|_| |_| |_|\__,_|_| |_|_|    \__, |")
    print("                                           __/ |")
    print("                                          |___/ ")
    print("")
    print("")
    #print("    Contributors: Felix Bernhardt  (JLU)")
    print("    Started at: "+datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))
    print("")
    
    #
    from parserArgs import args
    disps = [-1, 1]

    if args.displace == True:
        print("[__main__]: Displacing modes " + str(args.modelist))
        displace(args.modelist, args.stepsize, args.program, disps)
        sys.exit(1)
    
    if args.tensors == True:
        print("[__main__]: Calculating Raman tensors of modes " + str(args.modelist))
        calcTensors(args.modelist, args.program, args.stepsize, disps)

    if args.spectrum == True:
        print("[__main__]: Calculating Raman spectrum")
        calcSpectrum(args.modelist, args.laser, args.temperature, args.smearing) 
    
    if args.plot == True:
        print("[__main__]: Plotting Raman spectrum")
        plotSpectrum(args.laser, args.porto)
        
    sys.exit(1)
#
